# Generated by Django 2.2.5 on 2019-10-06 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plumber', '0011_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='hire',
            fields=[
                ('hire_id', models.AutoField(primary_key=True, serialize=False)),
                ('hire_product', models.CharField(choices=[(0, 'plumber'), (1, 'electricians'), (2, 'repairer')], max_length=50)),
                ('hire_status', models.CharField(choices=[(0, 'Aborted'), (1, 'Confirm')], max_length=50)),
                ('hire_type', models.CharField(choices=[(0, 'without equipments'), (1, 'with equipments')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plumber.user')),
            ],
        ),
    ]
