# Generated by Django 2.2.5 on 2019-10-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='hire_product',
            field=models.IntegerField(choices=[(0, 'plumber'), (1, 'electricians'), (2, 'repairer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hire',
            name='hire_status',
            field=models.IntegerField(choices=[(0, 'Aborted'), (1, 'Confirm')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hire',
            name='hire_type',
            field=models.IntegerField(choices=[(0, 'without equipments'), (1, 'with equipments')], max_length=50),
        ),
    ]
