# Generated by Django 2.2.5 on 2019-10-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0003_hire_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='hire_product',
            field=models.CharField(max_length=50),
        ),
    ]
