# Generated by Django 2.2.5 on 2019-10-06 19:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plumber', '0011_delete_orders'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=30)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[(1, 'completed'), (0, 'InProcess')], max_length=50, null=True)),
                ('days', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('product_type', models.CharField(choices=[(0, 'perday'), (1, 'fullprocess')], max_length=50, null=True)),
                ('order_type', models.CharField(choices=[(0, 'without equipments'), (1, 'with equipments')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plumber.user')),
            ],
        ),
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('totol_cost', models.FloatField()),
                ('profit', models.FloatField()),
                ('noemp', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plumber.user')),
            ],
        ),
    ]
