# Generated by Django 2.2.5 on 2019-10-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191007_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_type',
            field=models.IntegerField(choices=[(0, 'without equipments'), (1, 'with equipments')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(1, 'completed'), (0, 'InProcess')], max_length=50, null=True),
        ),
    ]
