# Generated by Django 2.2.5 on 2019-10-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_detail_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='noemp',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='totol_cost',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='user',
        ),
    ]
