# Generated by Django 2.2.5 on 2019-10-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20191026_2043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order_detail',
        ),
    ]
