# Generated by Django 2.2.5 on 2019-10-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_delete_order_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.AutoField(default='username', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.CharField(default='product', max_length=30),
        ),
    ]
