# Generated by Django 2.2.5 on 2019-10-26 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plumber', '0011_delete_orders'),
        ('employes', '0002_auto_20191026_2055'),
        ('orders', '0008_auto_20191026_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('totol_cost', models.FloatField()),
                ('profit', models.FloatField()),
                ('noemp', models.IntegerField(default=0)),
                ('employes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employes.employes')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plumber.user')),
            ],
        ),
    ]
