# Generated by Django 2.2.5 on 2019-10-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employes',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(default='password', max_length=50)),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('work', models.CharField(choices=[('plumber', 'plumber'), ('electricians', 'electricians'), ('repairer', 'repairer')], max_length=50, null=True)),
                ('Phonenumber', models.IntegerField(default=7741910761, max_length=10)),
                ('Phonenumber2', models.IntegerField(default=7741910761, max_length=10)),
                ('email', models.EmailField(default='ayanshaikh7187@gmail.com', max_length=30)),
                ('state', models.CharField(default='state', max_length=30)),
                ('address1', models.TextField(default='address')),
                ('address2', models.TextField(default='address')),
                ('city', models.CharField(default='city', max_length=30)),
                ('zipcode', models.IntegerField(default=411042)),
                ('dob', models.DateField(null=True)),
                ('age', models.IntegerField(default=0)),
                ('contact', models.IntegerField(default=0)),
                ('addharno', models.IntegerField(default=0)),
                ('adharimage', models.ImageField(default='default.jpg', upload_to='adhar_pics')),
                ('profile', models.ImageField(default='default.jpg', upload_to='emp_pics')),
            ],
        ),
    ]
