# Generated by Django 2.2.5 on 2019-10-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employes',
            name='firstname',
            field=models.CharField(default='firstname', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employes',
            name='lastname',
            field=models.CharField(default='lastname', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employes',
            name='username',
            field=models.CharField(default='username', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employes',
            name='work',
            field=models.CharField(choices=[('plumber', 'plumber'), ('electricians', 'electricians'), ('repairer', 'repairer')], default='work', max_length=50, null=True),
        ),
    ]
