# Generated by Django 2.2.5 on 2019-09-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.TextField(max_length=25)),
                ('Phonenumber', models.IntegerField(max_length=10)),
                ('Phonenumber2', models.IntegerField(max_length=10)),
                ('email', models.TextField(max_length=30)),
                ('state', models.TextField(max_length=30)),
                ('address1', models.TextField(max_length=50)),
                ('address12', models.TextField(max_length=30)),
                ('city', models.TextField(max_length=30)),
                ('zipcode', models.IntegerField(max_length=20)),
            ],
        ),
    ]
