# Generated by Django 2.2.5 on 2019-09-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumber', '0002_auto_20190928_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='testing321', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
