# Generated by Django 2.2.5 on 2019-09-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumber', '0003_auto_20190928_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='address12',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=30),
        ),
    ]
