# Generated by Django 2.2.5 on 2019-09-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumber', '0004_auto_20190928_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=30),
        ),
    ]
