# Generated by Django 2.2.5 on 2019-09-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumber', '0005_auto_20190928_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Phonenumber',
            field=models.IntegerField(default=7741910761, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='Phonenumber2',
            field=models.IntegerField(default=7741910761, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='address1',
            field=models.TextField(default='address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address12',
            field=models.TextField(default='address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='city', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='ayanshaikh7187@gmail.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='firstname', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='lastname', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(default='state', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.IntegerField(default=411042),
        ),
    ]
