# Generated by Django 2.2.5 on 2019-10-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumber', '0006_auto_20190928_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
