# Generated by Django 2.2.5 on 2019-10-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plumber', '0007_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
    ]
