# Generated by Django 2.2.5 on 2019-10-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plumber', '0010_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
    ]
